SELECT LENGTH('SQL Expert') LEN
FROM DUAL;

SELECT*FROM DUAL;

SELECT LEN('SQL Expert')AS Len;

SELECT CONCAT (PLAYER_NAME,'축구선수') 선수명
FROM PLAYER;

SELECT PLAYER_NAME || '축구선수' 선수명
FROM PLAYER;

SELECT STADIUM_ID, DDD ||')'||TEL AS TEL, LENGTH (DDD||'-'||TEL) AS T_LEN
FROM STADIUM;

SELECT ENAME, ROUND(SAL/12,1) AS SAL_ROUND, TRUNC (SAL/12,1) AS SAL_TRUNC
FROM EMP;