SELECT TEAM_ID AS 팀ID,
    TO_NUMBER(ZIP_CODE1, '999')+TO_NUMBER(ZIP_CODE2,'999')AS 우편번호합
FROM TEAM;

SELECT MGR
FROM EMP
WHERE ENAME='SCOTT';

SELECT MGR
FROM EMP
WHERE ENAME='KING';

SELECT NVL(MGR,9999) AS MGR
FROM EMP
WHERE ENAME = 'KING';

SELECT NVL(MAX(MGR),9999) AS MGR
FROM EMP
WHERE ENAME = 'JSC';

SELECT PLAYER_NAME AS 선수명, POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키
FROM PLAYER
WHERE POSITION='MF';

SELECT PLAYER_NAME AS 선수명, POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키
FROM PLAYER
WHERE HEIGHT >=170;

SELECT PLAYER_NAME AS 선수명, POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키
FROM PLAYER
WHERE TEAM_ID IN ('K02', 'K07');

SELECT ENAME, JOB, DEPTNO
FROM EMP
WHERE (JOB, DEPTNO) IN (('MANAGER', 20), ('CLERK',30));


SELECT ENAME, JOB, DEPTNO
FROM EMP
WHERE JOB IN ('MANAGER', 'CLERK') AND DEPTNO IN (20,30);


SELECT PLAYER_NAME AS 선수명, POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키
FROM PLAYER
WHERE POSITION LIKE 'MF';


SELECT PLAYER_NAME AS 선수명, POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키
FROM PLAYER
WHERE PLAYER_NAME LIKE '장%';


SELECT PLAYER_NAME AS 선수명, POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키
FROM PLAYER
WHERE PLAYER_NAME LIKE '장_호';


SELECT PLAYER_NAME AS 선수명, POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키
FROM PLAYER
WHERE HEIGHT BETWEEN 170 AND 180;

SELECT PLAYER_NAME AS 선수명, POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키
FROM PLAYER
WHERE TEAM_ID = 'K02'
AND HEIGHT >= 170;

SELECT PLAYER_NAME AS 선수명, POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키
FROM PLAYER
WHERE TEAM_ID = 'K02'
AND NOT POSITION = 'MF'
AND NOT HEIGHT BETWEEN 175 AND 185;

SELECT POSITION AS 포지션, COUNT (*) AS 인원수, COUNT (HEIGHT) AS 키대상,
    MAX (HEIGHT) AS 최대키, MIN (HEIGHT) AS 최소키,
    ROUND (AVG (HEIGHT),2) AS 평균키
FROM PLAYER
GROUP BY POSITION;

SELECT POSITION AS 포지션, ROUND (AVG (HEIGHT),2) AS 평균키
FROM PLAYER
GROUP BY POSITION
HAVING AVG (HEIGHT) >= 180;


SELECT ENAME AS 사원명, DEPTNO AS 부서번호,
    EXTRACT (MONTH FROM HIREDATE) AS 입사월, SAL AS 급여
FROM EMP;


SELECT ROUND (AVG (CASE WHEN POSITION = 'MF' THEN HEIGHT END),2) AS 미드필더,
        ROUND (AVG (CASE WHEN POSITION = 'FW' THEN HEIGHT END),2) AS 포원드,
        ROUND (AVG (CASE WHEN POSITION = 'DF' THEN HEIGHT END),2) AS 디펜더,
        ROUND (AVG (CASE WHEN POSITION = 'GK' THEN HEIGHT END),2) AS 골키퍼,
        ROUND (AVG (HEIGHT),2) 전체평균키
FROM PLAYER;
        
        
SELECT PLAYER_NAME AS 선수명, POSITION AS 포지션, BACK_NO AS 백넘버
FROM PLAYER
ORDER BY PLAYER_NAME DESC;


SELECT DNAME, LOC, DEPTNO
FROM DEPT
ORDER BY DNAME, LOC, DEPTNO DESC;

SELECT JOB, SUM(SAL) AS SALARY_SUM
    FROM EMP
GROUP BY JOB
    HAVING SUM(SAL)>5000
ORDER BY SUM(SAL);


SELECT PLAYER.PLAYER_NAME, PLAYER.BACK_NO, PLAYER.TEAM_ID,
    TEAM.TEAM_NAME, TEAM.REGION_NAME
FROM PLAYER, TEAM
WHERE TEAM.TEAM_ID=PLAYER.TEAM_ID;