 /* 
 오!리뷰 전체 테이블 
 마지막 수정 날짜 : 2018/04/25
 */

-- SELECT TABLE
SELECT * FROM OH_MEMBER;
SELECT * FROM BBS_EXPERIENCE;
SELECT * FROM APPLY_CAMPAIN;
SELECT * FROM REVIEW;
SELECT * FROM BBS_CTS;
SELECT *  FROM CTS_REPLY;

-- DROP TABLE
DROP TABLE OH_MEMBER;
DROP TABLE BBS_EXPERIENCE;
DROP TABLE APPLY_CAMPAIN;
DROP TABLE REVIEW;
DROP TABLE BBS_CTS;
DROP TABLE CTS_REPLY;

-- DROP SEQ
DROP SEQUENCE BBS_EXPERIENCE_SEQ;
DROP SEQUENCE APPLY_CAMPAIN_SEQ;
DROP SEQUENCE REVIEW_SEQ;
DROP SEQUENCE BBS_CTS_SEQ;
DROP SEQUENCE CTS_REPLY_SEQ;

-- 회원
CREATE TABLE OH_MEMBER(
member_id NVARCHAR2(50),
member_password NVARCHAR2(50) NOT NULL,
member_name NVARCHAR2(50) NOT NULL,
member_blog NVARCHAR2(50) NOT NULL,
member_email NVARCHAR2(100) UNIQUE,
member_postcode NVARCHAR2(200),
member_address NVARCHAR2(200) NOT NULL,
member_address_detail NVARCHAR2(200) NOT NULL,
UPDATEDATE NVARCHAR2(50),
member_img NVARCHAR2(100) NOT NULL,
PRIMARY KEY(member_id));

-- 캠페인
CREATE SEQUENCE BBS_EXPERIENCE_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE BBS_EXPERIENCE(
EXP_BBS_NUMBER NUMBER PRIMARY KEY,
EXP_CATEGORIE NVARCHAR2(50) NOT NULL,
EXP_CATEGORIE_DETAIL NVARCHAR2(50) NOT NULL,
EXP_ADD_CITY NVARCHAR2(50) NOT NULL,
EXP_ADD_DETAIL NVARCHAR2(50) NOT NULL,
EXP_RECRUIT_MEM NUMBER,
EXP_APPLY_MEM NUMBER DEFAULT 0,
EXP_RECUIT_DATE NVARCHAR2(50),
EXP_TITLE NVARCHAR2(50) NOT NULL,
CONTENT_EXPERIENCE NVARCHAR2(2000) NOT NULL,
CONTENT_ENTERPRICE NVARCHAR2(2000) NOT NULL,
EXP_HIT NUMBER DEFAULT 0,
EXP_IMG NVARCHAR2(50));

-- 캠페인 신청서
CREATE SEQUENCE APPLY_CAMPAIN_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE APPLY_CAMPAIN(
APPLY_NUMBER NUMBER,
EXP_BBS_NUMBER NUMBER NOT NULL,
MEMBER_ID NVARCHAR2(50) NOT NULL,
EXP_TITLE NVARCHAR2(50) NOT NULL,
APPLY_NAME NVARCHAR2(50) NOT NULL,
APPLY_TEL NVARCHAR2(50) NOT NULL,
APPLY_BLOG NVARCHAR2(50) NOT NULL UNIQUE,
APPLY_RESULT NVARCHAR2(50) DEFAULT '대기',
PRIMARY KEY(APPLY_NUMBER));

-- 리뷰
CREATE SEQUENCE REVIEW_SEQ START WITH 1 INCREMENT BY 1;
create table REVIEW(
REV_NUM NUMBER PRIMARY KEY,
EXP_BBS_NUMBER NUMBER NOT NULL,
EXP_TITLE  NVARCHAR2(50) NOT NULL,
MEMBER_ID  NVARCHAR2(50) NOT NULL,
REV_CONTENT nvarchar2(2000) NOT NULL,
REV_DATE NVARCHAR2(50));

-- 1:1 문의
CREATE SEQUENCE BBS_CTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE BBS_CTS(
CTS_NUMBER NUMBER PRIMARY KEY,
MEMBER_ID NVARCHAR2(100) NOT NULL,
CTS_TITLE NVARCHAR2(100) NOT NULL,
CTS_CATEGORIE NVARCHAR2(100) NOT NULL,
CTS_CONTENT NVARCHAR2(1000) NOT NULL,
CTS_WRITE_DATE NVARCHAR2(100) NOT NULL);

-- 1:1 문의 댓글
CREATE SEQUENCE CTS_REPLY_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE CTS_REPLY(
CTS_RP_NUMBER NUMBER PRIMARY KEY,
CTS_NUMBER NUMBER NOT NULL,
CTS_RP_CONTENT NVARCHAR2(1000) NOT NULL,
CTS_RP_DATE NVARCHAR2(100));                                    
